entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: https
          scheme: https

  https:
    address: ":443"

serverTransport:
  insecureSkipVerify: true
certificatesResolvers:
  cloudflare:
    acme:
      email: bouquiauxnico@gmail.com
      storage: acme.json

#       -- (Optional) Remove this section, when using DNS Challenge
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    network: traefik

  
api:
  dashboard: true
  insecure: true