version: '3'
services:
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  build: ./api
  container_name: api
  ports:
    - "3000:3000"
    